# -*- coding: utf-8 -*-
"""cvlab 6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kLBlBnulJ8Nha1-OxYl7JbkMLD1TZWM5
"""

import cv2
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

r_min = 100
r_max = 200
img = cv2.imread("/content/images.jpg")
if img is None:
    print("Error: Could not load image from /content/images.jpg ")
else:
    slicing_with_bg = np.zeros(img.shape[:2], dtype=np.uint8)
    slicing_without_bg = np.zeros(img.shape[:2], dtype=np.uint8)
    if len(img.shape) == 3:
        img_for_comparison = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    else:
        img_for_comparison = img

    for i in range(img_for_comparison.shape[0]):
        for j in range(img_for_comparison.shape[1]):
            pixel_value = img_for_comparison[i, j]

            if r_min <= pixel_value <= r_max:
                slicing_with_bg[i, j] = 255
                slicing_without_bg[i, j] = 255
            else:
                slicing_with_bg[i, j] = 0
    plt.figure(figsize=(15, 5))

    plt.subplot(1, 3, 1)
    plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
    plt.title("Original Image")
    plt.axis('off')

    plt.subplot(1, 3, 2)
    plt.imshow(slicing_with_bg, cmap='gray')
    plt.title("Slice with Background")
    plt.axis('off')

    plt.subplot(1, 3, 3)
    plt.imshow(slicing_without_bg, cmap='gray')
    plt.title("Slice without Background")
    plt.axis('off')

    plt.show()